trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Install Java & JMeter'
  inputs:
    targetType: 'inline'
    script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jre wget unzip
      wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.3.zip
      unzip apache-jmeter-5.6.3.zip
      export JMETER_HOME=$PWD/apache-jmeter-5.6.3
      export PATH=$JMETER_HOME/bin:$PATH

- task: Bash@3
  displayName: 'Run JMeter Test'
  inputs:
    targetType: 'inline'
    script: |
      mkdir -p results
      jmeter -n -t bestbuy-test-plan.jmx -l results/result.jtl -e -o results/report

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'results'
    artifact: 'JMeterResults'
    publishLocation: 'pipeline'
